CFLAGS = -O3 -I.
CC = gcc

TARGETS = test01 test02 test03 test04 test05 test06 test07 test08 \
	  test09 test10 test11 test12 test13

all:
	$(CC) $(CFLAGS) -o test01 test01.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test02 test02.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test03 test03.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test04 test04.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test05 test05.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test06 test06.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test07 test07.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test08 test08.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test09 test09.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test10 test10.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test11 test11.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test12 test12.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm
	$(CC) $(CFLAGS) -o test13 test13.c -lmcegraphics -lz -lnetpbm -lfftw3 -lm

clean:
	rm -f $(TARGETS) tiger2.ppm tiger3.ppm


